name: Node CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Set up pnpm
        run: npm install --global "$(node -p 'require("./package.json").packageManager')"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check build
        run: pnpm run check
        env:
          CI: true
      - name: Upload Pages artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    concurrency:
      group: github-pages
      cancel-in-progress: false
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
