name: Node CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: install, build, and deploy
        run: |
          npm i -g pnpm
          pnpm i
          pnpm run clean
          pnpm run build
          export COMMIT_HASH=`git log -1 --pretty=format:"%H"`
          pnpm run deploy
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
